spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/hochi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always
